### PR TITLE
DLSPP-120

### PR DESCRIPTION
**Pull request by ehanson8**
#### What does this PR do?
The first commit refactors the `receive` method to ensure all SQS messages are retrieved from a queue:
* Add while loop to ensure all messages are received from the queue
* Add error message fixture
* Rename existing SQS message body fixture

The second commit adds a listener function that logs successes and errors:
* Add listen function to retrieve and log messages from SQS queue
* Add corresponding unit tests

#### Helpful background context
This functionality should set us up for testing with the DSS test instance.

#### How can a reviewer manually see the effects of these changes?
Run the unit tests with `pipenv run pytest`

#### What are the relevant tickets?
* https://mitlibraries.atlassian.net/browse/DLSPP-120

#### Requires Database Migrations?
NO

#### Includes new or updated dependencies?
NO

### CODE REVIEW

**Comment by osmandin** [comment]
1. Right now this is just listening for all messages and not checking for any wiley specific messages, right.
2. If not what happens to  Wiley messages after they read? Presumably they should be deleted from the queue or expired/purged somehow.

**Comment by ehanson8** [comment]
1. Wiley will have it's own separate output queue in DSS so no filtering is requiring
2. I will confirm with Jeremy but what I believe he told me was that the way the queues were set up, the messages disappear after they are retrieved. I'll get back to you on that

**Comment by ehanson8** [comment]
I misunderstood, the Ruby code they're using takes care of the messages but I will add in a delete method and call that method after the message is logged. I'll tag you when I have the new commit

**Comment by ehanson8** [comment]
@osmandin Added a delete process after logging, ready for review again

**Review by osmandin — CHANGES_REQUESTED** [review]

**Review by osmandin — APPROVED** [review]

**Review by osmandin — APPROVED** [review]

**Pull request merged**
